spring:
  application:
    name: notificacaoConsumer
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8082

app:
  email:
    remetente: posfiapteam35@gmail.com
    senha: jbvp ugel gull ksqr

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://controle-servicos:8761/eureka
  instance:
    hostname: notificacaoConsumer