spring:
  application:
    name: notificacaoConsumer
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost